export const ContactActionTypes = {
    CONTACT_REGISTRATION_START: 'CONTACT_REGISTRATION_START',
    CONTACT_REGISTRATION_SUCCESS: 'CONTACT_REGISTRATION_SUCCESS',
    CONTACT_REGISTRATION_FAILURE: 'CONTACT_REGISTRATION_FAILURE',
}